ALTER TABLE CheckIO DROP CONSTRAINT IF EXISTS ck_checkio_checkin_type;
ALTER TABLE CheckIO DROP COLUMN IF EXISTS note;
ALTER TABLE CheckIO DROP COLUMN IF EXISTS factory_name;
ALTER TABLE CheckIO DROP COLUMN IF EXISTS checkin_type;
